version: "3"

services:
  twilio-token-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: twilio-token:dev
    container_name: dev
    command: pnpm start
    ports:
      - 8589:3000
